sensor:
  - name: StromGedacht status code
    unique_id: stromgedacht_status_code
    platform: rest
    resource_template: https://api.stromgedacht.de/v1/now?zip=76131
    headers:
      User-Agent: HomeAssistant
      Content-Type: application/json
    json_attributes:
      - state
    value_template: >
      {{ value_json['state'] }}

template:
  - sensor:
      - name: "StromGedacht status message"
        state: >
          {% set mapper =  {
              '1' : 'Normalbetrieb - Du musst nichts weiter tun',
              '2' : 'Verbrauch vorverlegen - Strom jetzt nutzen',
              '3' : 'Verbrauch reduzieren - Gemeinsam Kosten und CO2 sparen',
              '4' : 'Verbrauch reduzieren - Strommangel verhindern' } %}
          {% set state =  states('sensor.stromgedacht_status_code') %}
          {{ mapper[state] if state in mapper else 'N/A' }}
